before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ULgVNZmMrE0DVSepA17TQsbFrfCUeUOJlNrTq0tdlwtdqxG/IWX2/tkubaYG6as7P2RGiGb4+WE3SrjX4x9oxuu6wdyiTA8dtMWYcvb9WspYPgMuCULFhoz/4xIyakCMX2ExXOS+5yVR6WsPKZvlPxVurGRCEv6JRaIFPOjxF/Lo3ZXdCxUGa0h6m/twcR/NCeCBqJQUCvhYc/LEyIQL+kMn2mTWzo6qI/g929aaiKP/SdfN5ZQQbLmSkdhIqSVIlG0O9rlXVUlHNESDBkmQkdv1I8E01qpbvoAVCtHDr3m7EYyxS6Hhl3W+XIA73oTRJaJzRPCvg5X9RTY5h+pNQlZGXMrxqO6FzJgrDwCNGrM6h9XVamjaGf8py6GCtWxUR6g+qcGfxr17yt7RdZhYycCsP1iKKweoAE8AyZgVrgQvvSprBiFRJDzC6nHyGpUVhwO0XMmbv5a2I58kCJgeNujKTR38Y2BoYnYh/K7bGj0y8jz3nOf3ZU16Asqjc7+NfFyfrwfITM27Xt1xw+qkXrKNH5YcJZsYjySvgXufahvEw7tpnBbwwarL5MJc9Rmv2LS02V3yRUBe7+HX4poO1aCG0Ut0PaVp/xcEp8wcuONlPtQVvVJwslSksEPe26hwdHxXmGoO/UD//koMUDUWwdbJ93lecg1mVAoY1RggiRQ= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
